const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const flags = if (optimize == .Debug)
        &(common_flags ++ .{"-g"})
    else
        &common_flags;

    const lib = b.addStaticLibrary(.{
        .name = "mbedtls",
        .target = target,
        .optimize = optimize,
    });
    lib.addCSourceFiles(.{
        .root = b.path("library"),
        .files = &all_sources,
        .flags = flags,
    });
    lib.addIncludePath(b.path("include"));

    lib.linkLibC();

    lib.installHeadersDirectory(b.path("include"), ".", .{});

    b.installArtifact(lib);
}

const common_flags = [_][]const u8{
    "-Wall",
    "-Wextra",
    "-Wwrite-strings",
    "-Wmissing-prototypes",
    "-Wpointer-arith",
    "-Wimplicit-fallthrough",
    "-Wshadow",
    "-Wvla",
    "-Wformat=2",
    "-Wno-format-nonliteral",
    // asan
    // "-fsanitize=address",
    // "-fno-common",
    // "-fsanitize=undefined",
    // "-fno-sanitize-recover=all",
};

const all_sources = [_][]const u8{
    "aes.c",
    "aesce.c",
    "aesni.c",
    "aria.c",
    "asn1parse.c",
    "asn1write.c",
    "base64.c",
    "bignum.c",
    "bignum_core.c",
    "bignum_mod.c",
    "bignum_mod_raw.c",
    "block_cipher.c",
    "camellia.c",
    "ccm.c",
    "chacha20.c",
    "chachapoly.c",
    "cipher.c",
    "cipher_wrap.c",
    "cmac.c",
    "constant_time.c",
    "ctr_drbg.c",
    "debug.c",
    "des.c",
    "dhm.c",
    "ecdh.c",
    "ecdsa.c",
    "ecjpake.c",
    "ecp.c",
    "ecp_curves.c",
    "ecp_curves_new.c",
    "entropy.c",
    "entropy_poll.c",
    "error.c",
    "gcm.c",
    "hkdf.c",
    "hmac_drbg.c",
    "lmots.c",
    "lms.c",
    "md.c",
    "md5.c",
    "memory_buffer_alloc.c",
    "mps_reader.c",
    "mps_trace.c",
    "net_sockets.c",
    "nist_kw.c",
    "oid.c",
    "padlock.c",
    "pem.c",
    "pk.c",
    "pk_ecc.c",
    "pk_wrap.c",
    "pkcs12.c",
    "pkcs5.c",
    "pkcs7.c",
    "pkparse.c",
    "pkwrite.c",
    "platform.c",
    "platform_util.c",
    "poly1305.c",
    "psa_crypto.c",
    "psa_crypto_aead.c",
    "psa_crypto_cipher.c",
    "psa_crypto_client.c",
    "psa_crypto_driver_wrappers_no_static.c",
    "psa_crypto_ecp.c",
    "psa_crypto_ffdh.c",
    "psa_crypto_hash.c",
    "psa_crypto_mac.c",
    "psa_crypto_pake.c",
    "psa_crypto_rsa.c",
    "psa_crypto_se.c",
    "psa_crypto_slot_management.c",
    "psa_crypto_storage.c",
    "psa_its_file.c",
    "psa_util.c",
    "ripemd160.c",
    "rsa.c",
    "rsa_alt_helpers.c",
    "sha1.c",
    "sha256.c",
    "sha3.c",
    "sha512.c",
    "ssl_cache.c",
    "ssl_ciphersuites.c",
    "ssl_client.c",
    "ssl_cookie.c",
    "ssl_debug_helpers_generated.c",
    "ssl_msg.c",
    "ssl_ticket.c",
    "ssl_tls.c",
    "ssl_tls12_client.c",
    "ssl_tls12_server.c",
    "ssl_tls13_client.c",
    "ssl_tls13_generic.c",
    "ssl_tls13_keys.c",
    "ssl_tls13_server.c",
    "threading.c",
    "timing.c",
    "version.c",
    "version_features.c",
    "x509.c",
    "x509_create.c",
    "x509_crl.c",
    "x509_crt.c",
    "x509_csr.c",
    "x509write.c",
    "x509write_crt.c",
    "x509write_csr.c",
};

const all_headers = [_][]const u8{
    "mbedtls/aes.h",
    "mbedtls/aria.h",
    "mbedtls/asn1.h",
    "mbedtls/asn1write.h",
    "mbedtls/base64.h",
    "mbedtls/bignum.h",
    "mbedtls/block_cipher.h",
    "mbedtls/build_info.h",
    "mbedtls/camellia.h",
    "mbedtls/ccm.h",
    "mbedtls/chacha20.h",
    "mbedtls/chachapoly.h",
    "mbedtls/check_config.h",
    "mbedtls/cipher.h",
    "mbedtls/cmac.h",
    "mbedtls/compat-2.x.h",
    "mbedtls/config_adjust_legacy_crypto.h",
    "mbedtls/config_adjust_legacy_from_psa.h",
    "mbedtls/config_adjust_psa_from_legacy.h",
    "mbedtls/config_adjust_psa_superset_legacy.h",
    "mbedtls/config_adjust_ssl.h",
    "mbedtls/config_adjust_x509.h",
    "mbedtls/config_psa.h",
    "mbedtls/constant_time.h",
    "mbedtls/ctr_drbg.h",
    "mbedtls/debug.h",
    "mbedtls/des.h",
    "mbedtls/dhm.h",
    "mbedtls/ecdh.h",
    "mbedtls/ecdsa.h",
    "mbedtls/ecjpake.h",
    "mbedtls/ecp.h",
    "mbedtls/entropy.h",
    "mbedtls/error.h",
    "mbedtls/gcm.h",
    "mbedtls/hkdf.h",
    "mbedtls/hmac_drbg.h",
    "mbedtls/lms.h",
    "mbedtls/mbedtls_config.h",
    "mbedtls/md.h",
    "mbedtls/md5.h",
    "mbedtls/memory_buffer_alloc.h",
    "mbedtls/net_sockets.h",
    "mbedtls/nist_kw.h",
    "mbedtls/oid.h",
    "mbedtls/pem.h",
    "mbedtls/pk.h",
    "mbedtls/pkcs12.h",
    "mbedtls/pkcs5.h",
    "mbedtls/pkcs7.h",
    "mbedtls/platform.h",
    "mbedtls/platform_time.h",
    "mbedtls/platform_util.h",
    "mbedtls/poly1305.h",
    "mbedtls/private_access.h",
    "mbedtls/psa_util.h",
    "mbedtls/ripemd160.h",
    "mbedtls/rsa.h",
    "mbedtls/sha1.h",
    "mbedtls/sha256.h",
    "mbedtls/sha3.h",
    "mbedtls/sha512.h",
    "mbedtls/ssl.h",
    "mbedtls/ssl_cache.h",
    "mbedtls/ssl_ciphersuites.h",
    "mbedtls/ssl_cookie.h",
    "mbedtls/ssl_ticket.h",
    "mbedtls/threading.h",
    "mbedtls/timing.h",
    "mbedtls/version.h",
    "mbedtls/x509.h",
    "mbedtls/x509_crl.h",
    "mbedtls/x509_crt.h",
    "mbedtls/x509_csr.h",
    "psa/build_info.h",
    "psa/crypto.h",
    "psa/crypto_adjust_auto_enabled.h",
    "psa/crypto_adjust_config_dependencies.h",
    "psa/crypto_adjust_config_key_pair_types.h",
    "psa/crypto_adjust_config_synonyms.h",
    "psa/crypto_builtin_composites.h",
    "psa/crypto_builtin_key_derivation.h",
    "psa/crypto_builtin_primitives.h",
    "psa/crypto_compat.h",
    "psa/crypto_config.h",
    "psa/crypto_driver_common.h",
    "psa/crypto_driver_contexts_composites.h",
    "psa/crypto_driver_contexts_key_derivation.h",
    "psa/crypto_driver_contexts_primitives.h",
    "psa/crypto_extra.h",
    "psa/crypto_legacy.h",
    "psa/crypto_platform.h",
    "psa/crypto_se_driver.h",
    "psa/crypto_sizes.h",
    "psa/crypto_struct.h",
    "psa/crypto_types.h",
    "psa/crypto_values.h",
};
